version: '3.8'

services:
  helios:
    network_mode: host
    ipc: host
    tty: true
    privileged: true
    #restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: mnrobot.helios
    volumes:
      - ./:/temp
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    #  - "./src/food_placement_detection:/app/mnrobot_lunchbox/src/food_placement_detection"
    #  - "./src/mnrobot_msgs:/app/mnrobot_lunchbox/src/mnrobot_msgs"
    #ports:
    #  - "3000:3000"
    #env_file:
    #  - .env
    #  - DISPLAY=$DISPLAY
    tty: true
    privileged: true
    environment:
      #- ROS_MASTER_URI=http://172.16.0.3:11311
      #- ROS_IP=172.16.0.41
      #- ROS_MASTER_URI=http://192.168.101.71:11311
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
        # - ROS_WEBSOCKET_IP=192.168.100.90
    #command: ["/bin/bash", "-c", "roscore"]
    command: sleep infinity
    #command: ["ls"]
    #devices:
    #  - "/dev/video0:/dev/video0"
    #command: ["/bin/bash", "-c", "chmod u+x ./mnrobot_zivid/script/entrypoint.sh; /root/mnrobot_zivid/script/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
