version: '3.8'

services:
  helios:
    network_mode: host
    ipc: host
    tty: true
    privileged: true
    #restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: helios
    volumes:
      - ./:/temp
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    #ports:
    #  - "3000:3000"
    #env_file:
    #  - .env
    #  - DISPLAY=$DISPLAY
    tty: true
    privileged: true
    environment:
      #- ROS_MASTER_URI=http://0.0.0.0:11311
      #- ROS_IP=0.0.0.0
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
        # - ROS_WEBSOCKET_IP=0.0.0.0
    command: sleep infinity
    #devices:
    #  - "/dev/video0:/dev/video0"
    deploy:
      resources:
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
